### ISSUE TITLE
[Question] What program are you using to generate these file?

### ISSUE THREAD

**Issue by 007kevin** [leostd/Competitive-Programming#1]
Hello,

I was browsing your nice repo for Uva test inputs and came across this [directory](https://github.com/leostd/Competitive-Programming/blob/0bfac578a36b360e9de59c18c8b5b310e76e906e/WorkInProgress/UVa%20Online%20Judge/12124%20-%20Assemble/) for managing problems.

Just out of curiosity, what are you using to generate these `attic/config.json` files and how are these files being used?

Thanks :)

**Comment by leostd** [comment]
Hello 007kevin.

Those are auto-generated files by [acmX vscode plugin](https://marketplace.visualstudio.com/items?itemName=marx24.acmx).

Sorry for the (very) delayed answer.

**Comment by 007kevin** [comment]
Np thanks!
